apiVersion: batch/v1
kind: Job
metadata:
  name: setup-db
spec:
  template:
    spec:
      containers:
      - name: setup-db
        image: dgunjetti/setup-db
        command: ["sh", "setup-db.sh"]
      restartPolicy: Never
  backoffLimit: 6