Master:
  InstallPlugins:
    - kubernetes:1.13.0
    - workflow-job:2.31
    - workflow-aggregator:2.6
    - credentials-binding:1.17
    - git:3.9.1
  NumExecutors: 4
Agent:
  Enabled: false
Persistance:
  Enabled: false
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true


